### PR TITLE
WIP Translation de

### PR DESCRIPTION
**Pull request by silberzwiebel**
I've translated a bit more and are planning to do so in the next weeks. Let's see whether I find the time. 🤓
This PR is to join forces so that no-one is translating the same stuff all over. Happy about any feedback to the translation.

### CODE REVIEW

**Review by PeterNerlich — COMMENTED** [review]
very nice! I'm not sure about the `*innen` though, it feels weird and misplaced everytime. Do we need strict political correctness here?

**Comment by silberzwiebel** [comment]
I get the point and I'm also not entirely sure about it. But, to defend my current decision, I point to http://ncase.me/polygons-de/

**Review by PeterNerlich — COMMENTED** [review]
Nice, thanks so much! Yeah, half as expected I am now at the start of the exams without having done anything for this, though of course new ideas and projects continued to spring into existence which will continue to compete for attention even after...
I at least read the first part and I am impressed! Here and there is a comment where I feel like I could find a good equivalent expression or reinforce the original meaning if I just take the time and think about it... Take this as a heads up, I try not to abandon this. Despite you doing all of the work right now. You're really progressing nicely.
One thing I noticed, which is why I won't accept this PR just yet, on line 701 you accidentally deleted the first " of the `class"rarr"` on the `div` HTML tag. I didn't check whether that's the only occurrence of such a mistake.

**Comment by silberzwiebel** [comment]
Phew, that was a way larger amount of work than I expected in the first place. But it's completely translated now. I've updated the translations credits accordingly, assuming you are willing to proofread.
(Btw "political correctness" is a right-wing Kampfbegriff, impliyng someone is censoring something / or one cannot say some stuff, which is obviously false.)

**Comment by silberzwiebel** [comment]
Hey, not intending to put pressure on you but will you find some to time to proofread? If not, that's fine and I'll go ahead and open a PR at the original `crowds` repo on my own.

**Review by PeterNerlich — APPROVED** [review]
Okay! I got through it. got some notes, the trivial ones I'll just fix in a small commit soon.
Non-trivial ones here for discussion:
- Most prominently, there is a clear difference in how we both perceive the German language to work in written form, more precise, punctuation, explicitly concerning spaces around ellipsis (`...`). While I would say that I am correct in thinking that an ellipsis before and after some words which are discontinued or started without a proper start of a sentence *should not* be separated from it by a space, I am sure that you are just as certain that it *should* be. So this is simply a matter of further discussion. Maybe you know where we could look the more common way or standard up... (← see what I did there? :grin:)
- You often translate `Well` with `ok, ` and I feel divided about that. I don't really have a better suggestion at the moment though.
- The first time (I think...?) you translated ` PUZZLE TIME!` you did not capitalize your translation, later you did. I believe this was a mistake, but I'm not sure and thus want to get back to you on that.
- Say, for `bonding & bridging`, isn't `bonding` at least already "eingedeutscht"? I know business German is a hopeless mess regarding Denglish terms, but I would think this could already be in the public conscience. What do you think?
- On line 1277, 1289, 1321 and 1334 (and potentially more) you placed extra dots after mentioning the authors name which didn't appear in the original. I'm not sure what to do with it, was that a conscious decision?
- On line 1315, 1328 and 1378 you translated `evidence` with `Evidenz` — in contrast to `Bonding` this sounds rather unfamiliar to me. I would rather translate it as something like `Hinweise` — thoughts?

I think that's all. I'll pull this and change some trivial things. Again, thank you so much for your effort! Sorry for leaving you hanging for so long...

**Comment by silberzwiebel** [comment]
Great, thanks a lot for proofreading!

>    Most prominently, there is a clear difference in how we both perceive the German language to work in written form, more precise, punctuation, explicitly concerning spaces around ellipsis (...). While I would say that I am correct in thinking that an ellipsis before and after some words which are discontinued or started without a proper start of a sentence should not be separated from it by a space, I am sure that you are just as certain that it should be. So this is simply a matter of further discussion. Maybe you know where we could look the more common way or standard up... (← see what I did there? grin)

I followed typographic standards, see for instance here: https://typefacts.com/artikel/auslassungspunkte

>    You often translate Well with ok, and I feel divided about that. I don't really have a better suggestion at the moment though.

Maybe "Alles klar" or "Gut" at some places?

>    The first time (I think...?) you translated PUZZLE TIME! you did not capitalize your translation, later you did. I believe this was a mistake, but I'm not sure and thus want to get back to you on that.

Yes, this sounds more like a mistake than on purpose.

>    Say, for bonding & bridging, isn't bonding at least already "eingedeutscht"? I know business German is a hopeless mess regarding Denglish terms, but I would think this could already be in the public conscience. What do you think?

I just saw, its already in the Duden, so I guess, yes, it's eingedeutscht. So we should change all translations back to bonding then?

>    On line 1277, 1289, 1321 and 1334 (and potentially more) you placed extra dots after mentioning the authors name which didn't appear in the original. I'm not sure what to do with it, was that a conscious decision?

Yes, IMHO the dots should also be there in the original. et al. is an abbreviation of et alii: https://de.wikipedia.org/wiki/Et_al.

>    On line 1315, 1328 and 1378 you translated evidence with Evidenz — in contrast to Bonding this sounds rather unfamiliar to me. I would rather translate it as something like Hinweise — thoughts?

Hinweise sounds too weak to me. What about Belege?

**Comment by PeterNerlich** [comment]
- For `well`, I often understand it more in the role of the German `Nun, ...`, though I think it would feel bad if we use it more often than just a couple of times.
- I would vote for letting `bonding` stay `Bonding`, yes. To me it sounds better than any true German replacement.
- > Yes, IMHO the dots should also be there in the original. et al. is an abbreviation of et alii

  Maybe we should also make a separate pull request to the original then (if it is not already different)?
- `Belege` or maybe better `Indizien` if you like that.

**Comment by silberzwiebel** [comment]
>    For well, I often understand it more in the role of the German Nun, ..., though I think it would feel bad if we use it more often than just a couple of times.

- What about using "Nun" at some places and "Okay" at others?

>    I would vote for letting bonding stay Bonding, yes. To me it sounds better than any true German replacement.

Ok, fine with me. Are you going to change this or should I?

> >        Yes, IMHO the dots should also be there in the original. et al. is an abbreviation of et alii

>    Maybe we should also make a separate pull request to the original then (if it is not already different)?

Might be an idea, although English sometimes has other rules for not putting an abbreviation dot (e.g., for "Mr" I just had a document in my hand without a dot after Mr). But I never saw a missing dot for "et al." in scientific texts. I might open a PR then.

>    Belege or maybe better Indizien if you like that.

Let's use Belege. Indizien sounds to vague for me. Should I change this or do you?

**Comment by berndxfiedler** [comment]
Hi there. Former German teacher here, Berlin-based. So glad there's people already committed to this task. Mind if I join? :)

**Comment by PeterNerlich** [comment]
Not at all, this is perfect! We just finished translating though, so there will be only the usual teacher work to do... But feel free to go crazy correcting! (does this phrase even make sense?)

**Comment by berndxfiedler** [comment]
I hope I didn't trod on your toes, surely some of my fixes aren't pure typo-hunting or grammar or anything, but style issues. 

"Wisdom" should in some contexts not be translated into "Weisheit", but rather "Vernunft" in Opposition to "Wahnsinn". "Weisheit" is just not commonly used (in German, at least) and people might miss the message.

It's my first time contributing via GitHub, I hope I did follow protocol and didn't break anything. It's just that I'm into the topic "Trust in Information" at my working place (german NGO) and tripped over this piece of art and so much wanted to see a german translation in June, alas till now I didn't find the time to do it myself. Till now. So glad to have been part in this, hope u like my Input.

All the best from Berlin

**Comment by PeterNerlich** [comment]
Very nice! Don't worry, everything is fine and I value these style corrections even more. I have the problem of trying to find a matching translation as close to the original, since many nuances are not translatable already. Of course, this results in more unnatural translations, so I'm really happy to read your corrections and see how much more intuitive they sound. So thank you very much!

--------

As for breaking stuff on GitHub, don't worry! You cannot break other peoples' repos, only your own. In order to contribute to foreign projects, you first need to "fork" the repo from the other person, meaning to make a new repo belonging to you that starts off as a copy of the original one. GitHub defaults to that when trying to make a "commit" to a foreign repo, you probably didn't even notice it did that. There you can do your work without being interrupted, but that means that **1)** changes in the original repo do not appear in your fork automatically and **2)** changes in your fork so not appear in the original repo automatically (what a chaos if they would!)

So, how do you join the changes back together? You need to make a "pull request", so basically request the original owner to "pull" your changes back into his repo, merging your changes with what he potentially has done in the mean time. Of course, he can decide whether to do that or not — he can also decline or request changes. This page here is the pull request for the changes by silberzwiebel to my repo which he forked, while I forked my repo from ncase to start the german translation. You can see between the discussion, I as the owner reviewed it some times before approving and merging it. For more information about what is what, how everything works and so on, see the [GitHub Guides](https://guides.github.com/), especially the "Git Handbook" and "Forking Projects".

Okay, I hope I didn't bore you with what you may already know after all, but long story short, you need to make such a pull request for your changes now, too. (I could simply do that as well, but why not let you try if you're new?) For that, you need to go to your own fork and make sure you're on the right branch you want to submit the changes from. There you need to find and click "New pull request" — the source and target repos/branches should already be correctly picked by GitHub. Then, I'll approve and merge the changes and finally take care of submitting a pull request with our translation to the original repo by ncase.

**Comment by berndxfiedler** [comment]
Thanks. I understand I wouldn't harm the original in any case for me working on a copy all the time - I can see that. Still, there's logic and grammar and layout I can possibly destroy. Let's see what we got now ;)

I opened a pull request. If this didn't work, feel free to jump into action yourself. Would be a waste if this was left unfinished because of my inability to merge stuff.

**Comment by PeterNerlich** [comment]
Cheers guys, [the translation has been merged](https://github.com/ncase/crowds/pull/75#issuecomment-411460794)! Still, if you find anything else, don't hesitate to make a pull request against this or the original repository.

**Comment by silberzwiebel** [comment]
Hooray, many thanks!

**Pull request merged**
